author:
- given: Neil D.
  family: Lawrence
  institution: University of Cambridge
  gscholar: r3SJcvoAAAAJ
  twitter: lawrennd
  orcid: 0000-0001-9258-1030
  url: http://inverseprobability.com
layout: lecture
venue: Virtual (Zoom)
ipynb: True
talkcss: https://inverseprobability.com/assets/css/talks.css
postsdir: ../../../mlatcl/dsa/_lectures/
slidesdir: ../../../mlatcl/dsa/slides/
notesdir: ../../../mlatcl/dsa/_notes/
notebooksdir: ../../../mlatcl/dsa/_notebooks/
writediagramsdir: .
diagramsdir: ./slides/diagrams/
baseurl: "dsa/" # the subpath of your site, e.g. /blog/
url: "https://mlatcl.github.io/" # the base hostname & protocol for your site
transition: None
ghub:
- organization: lawrennd
  repository: talks
  branch: gh-pages
  directory: _dsa
  
